apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watchlist
  template:
    metadata:
      labels:
        app: watchlist
    spec:
      containers:
        - name: watchlist
          image: watchlist:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000